swagger: '2.0'
info:
  title: Backend API
  version: 1.0.0
  description: REST API with User and Post resources

host: localhost:3000
basePath: /api/v1
schemes:
  - http

securityDefinitions:
  bearerAuth:
    type: apiKey
    name: Authorization
    in: header

definitions:
  User:
    type: object
    properties:
      id:
        type: integer
      email:
        type: string
      name:
        type: string
      username:
        type: string
      phone:
        type: string
      website:
        type: string
      createdAt:
        type: string
        format: date-time
      updatedAt:
        type: string
        format: date-time
    required:
      - email
      - name
      - username

  Post:
    type: object
    properties:
      id:
        type: integer
      title:
        type: string
      body:
        type: string
      authorId:
        type: integer
      createdAt:
        type: string
        format: date-time
      updatedAt:
        type: string
        format: date-time
    required:
      - title
      - body
      - authorId

security:
  - bearerAuth: []

paths:
  /users:
    get:
      summary: List all users
      responses:
        '200':
          description: List of users
          schema:
            type: array
            items:
              $ref: '#/definitions/User'
    post:
      summary: Create a new user
      parameters:
        - name: user
          in: body
          required: true
          schema:
            $ref: '#/definitions/User'
      responses:
        '201':
          description: User created
          schema:
            $ref: '#/definitions/User'

  /users/{id}:
    parameters:
      - name: id
        in: path
        required: true
        type: integer
    get:
      summary: Get user by ID
      responses:
        '200':
          description: User found
          schema:
            $ref: '#/definitions/User'
    put:
      summary: Update user
      parameters:
        - name: user
          in: body
          required: true
          schema:
            $ref: '#/definitions/User'
      responses:
        '200':
          description: User updated
          schema:
            $ref: '#/definitions/User'
    patch:
      summary: Patch user
      parameters:
        - name: user
          in: body
          required: true
          schema:
            $ref: '#/definitions/User'
      responses:
        '200':
          description: User patched
          schema:
            $ref: '#/definitions/User'
    delete:
      summary: Delete user
      responses:
        '204':
          description: User deleted

  /posts:
    get:
      summary: List all posts
      responses:
        '200':
          description: List of posts
          schema:
            type: array
            items:
              $ref: '#/definitions/Post'
    post:
      summary: Create a new post
      parameters:
        - name: post
          in: body
          required: true
          schema:
            $ref: '#/definitions/Post'
      responses:
        '201':
          description: Post created
          schema:
            $ref: '#/definitions/Post'

  /posts/{id}:
    parameters:
      - name: id
        in: path
        required: true
        type: integer
    get:
      summary: Get post by ID
      responses:
        '200':
          description: Post found
          schema:
            $ref: '#/definitions/Post'
    put:
      summary: Update post
      parameters:
        - name: post
          in: body
          required: true
          schema:
            $ref: '#/definitions/Post'
      responses:
        '200':
          description: Post updated
          schema:
            $ref: '#/definitions/Post'
    patch:
      summary: Patch post
      parameters:
        - name: post
          in: body
          required: true
          schema:
            $ref: '#/definitions/Post'
      responses:
        '200':
          description: Post patched
          schema:
            $ref: '#/definitions/Post'
    delete:
      summary: Delete post
      responses:
        '204':
          description: Post deleted 