name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      sqlserver:
        image: mcr.microsoft.com/mssql/server:2022-latest
        env:
          ACCEPT_EULA: Y
          SA_PASSWORD: ${{ secrets.MSSQL_SA_PASSWORD }}
          MSSQL_PID: Developer
        ports:
          - 1433:1433
        options: >-
          --health-cmd "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P ${{ secrets.MSSQL_SA_PASSWORD }} -Q 'SELECT 1'"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v2

    - name: Setup Bun
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: latest

    - name: Install dependencies
      run: bun install

    - name: Generate Prisma Client
      run: bunx prisma generate

    - name: Run migrations
      run: bunx prisma migrate deploy
      env:
        DATABASE_URL: sqlserver://localhost:1433;database=test_db;user=sa;password=${{ secrets.MSSQL_SA_PASSWORD }};trustServerCertificate=true;

    - name: Build
      run: bun run build

    - name: Docker Build
      run: docker build -t backend-api .

    - name: Docker Push
      if: github.ref == 'refs/heads/main'
      run: |
        echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
        docker tag backend-api ${{ secrets.DOCKER_USERNAME }}/backend-api:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/backend-api:latest 